export type Crypto = { id: string; symbol: string; name: string }

export const CRYPTOS: Crypto[] = [
  { id: "bitcoin", symbol: "BTC", name: "Bitcoin" },
  { id: "ethereum", symbol: "ETH", name: "Ethereum" },
  { id: "tether", symbol: "USDT", name: "Tether" },
  { id: "binancecoin", symbol: "BNB", name: "BNB" },
  { id: "solana", symbol: "SOL", name: "Solana" },
  { id: "ripple", symbol: "XRP", name: "XRP" },
  { id: "usd-coin", symbol: "USDC", name: "USD Coin" },
  { id: "dogecoin", symbol: "DOGE", name: "Dogecoin" },
  { id: "cardano", symbol: "ADA", name: "Cardano" },
  { id: "tron", symbol: "TRX", name: "TRON" },
  { id: "avalanche-2", symbol: "AVAX", name: "Avalanche" },
  { id: "shiba-inu", symbol: "SHIB", name: "Shiba Inu" },
  { id: "polkadot", symbol: "DOT", name: "Polkadot" },
  { id: "chainlink", symbol: "LINK", name: "Chainlink" },
  { id: "bitcoin-cash", symbol: "BCH", name: "Bitcoin Cash" },
  { id: "litecoin", symbol: "LTC", name: "Litecoin" },
  { id: "near", symbol: "NEAR", name: "NEAR Protocol" },
  { id: "uniswap", symbol: "UNI", name: "Uniswap" },
  { id: "stellar", symbol: "XLM", name: "Stellar" },
  { id: "monero", symbol: "XMR", name: "Monero" },
  { id: "cosmos", symbol: "ATOM", name: "Cosmos" },
  { id: "ethereum-classic", symbol: "ETC", name: "Ethereum Classic" },
  { id: "filecoin", symbol: "FIL", name: "Filecoin" },
  { id: "hedera-hashgraph", symbol: "HBAR", name: "Hedera" },
  { id: "algorand", symbol: "ALGO", name: "Algorand" },
  { id: "aptos", symbol: "APT", name: "Aptos" },
  { id: "vechain", symbol: "VET", name: "VeChain" },
  { id: "internet-computer", symbol: "ICP", name: "Internet Computer" },
  { id: "cronos", symbol: "CRO", name: "Cronos" },
  { id: "the-sandbox", symbol: "SAND", name: "The Sandbox" },
]
